image: robertcnelson/debian-bullseye-slim-ti-linux-kernel-dev:latest

build:
  stage: build
  script:
    - cp -v system.sh.sample system.sh
    - echo "AUTO_BUILD=1" >> system.sh
    - echo "CORES=12" >> system.sh
    - ./build_deb.sh
  artifacts:
    paths:
      - "deploy/linux-image-*.deb"

